apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: masterdnsoperatorconfigs.masterdns.operator.openshift.io
spec:
  group: masterdns.operator.openshift.io
  names:
    kind: MasterDNSOperatorConfig
    plural: masterdnsoperatorconfigs
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            automaticUpdates:
              type: boolean
            logLevel:
              type: string
            managementState:
              type: string
          required:
          - managementState
          - automaticUpdates
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            generations:
              items:
                properties:
                  group:
                    type: string
                  hash:
                    type: string
                  lastGeneration:
                    format: int64
                    type: integer
                  name:
                    type: string
                  namespace:
                    type: string
                  resource:
                    type: string
                required:
                - group
                - resource
                - namespace
                - name
                - lastGeneration
                - hash
                type: object
              type: array
            observedGeneration:
              format: int64
              type: integer
            readyReplicas:
              format: int32
              type: integer
            version:
              type: string
          required:
          - version
          - readyReplicas
          - generations
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
