apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: masterdnsoperatorconfigs.masterdns.operator.openshift.io
spec:
  version: v1alpha1
  group: masterdns.operator.openshift.io
  names:
    kind: MasterDNSOperatorConfig
    plural: masterdnsoperatorconfigs
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            imagePullPolicy:
              type: string
            imagePullSpec:
              type: string
            logging:
              properties:
                level:
                  format: int64
                  type: integer
                vmodule:
                  type: string
              required:
              - level
              - vmodule
              type: object
            managementState:
              type: string
            version:
              type: string
          required:
          - managementState
          - imagePullSpec
          - imagePullPolicy
          - version
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            currentVersionAvailability:
              properties:
                errors:
                  items:
                    type: string
                  type: array
                generations:
                  items:
                    properties:
                      group:
                        type: string
                      lastGeneration:
                        format: int64
                        type: integer
                      name:
                        type: string
                      namespace:
                        type: string
                      resource:
                        type: string
                    required:
                    - group
                    - resource
                    - namespace
                    - name
                    - lastGeneration
                    type: object
                  type: array
                readyReplicas:
                  format: int32
                  type: integer
                updatedReplicas:
                  format: int32
                  type: integer
                version:
                  type: string
              required:
              - version
              - updatedReplicas
              - readyReplicas
              - errors
              - generations
              type: object
            observedGeneration:
              format: int64
              type: integer
            state:
              type: string
            targetVersionAvailability:
              properties:
                errors:
                  items:
                    type: string
                  type: array
                generations:
                  items:
                    properties:
                      group:
                        type: string
                      lastGeneration:
                        format: int64
                        type: integer
                      name:
                        type: string
                      namespace:
                        type: string
                      resource:
                        type: string
                    required:
                    - group
                    - resource
                    - namespace
                    - name
                    - lastGeneration
                    type: object
                  type: array
                readyReplicas:
                  format: int32
                  type: integer
                updatedReplicas:
                  format: int32
                  type: integer
                version:
                  type: string
              required:
              - version
              - updatedReplicas
              - readyReplicas
              - errors
              - generations
              type: object
            taskSummary:
              type: string
          type: object
