kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: master-dns-operator
subjects:
- kind: ServiceAccount
  name: master-dns-operator
  namespace: openshift-master-dns
roleRef:
  kind: Role
  name: master-dns-operator
  apiGroup: rbac.authorization.k8s.io
