apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: ["masterdns.operator.openshift.io"]
  resources: ["dnsendpoints"]
  verbs: ["get","list","watch","create","update","patch","delete"]
